const js = require('@eslint/js');
const tseslint = require('@typescript-eslint/eslint-plugin');
const tsparser = require('@typescript-eslint/parser');
const reactHooks = require('eslint-plugin-react-hooks');
const globals = require('globals');

/**
 * Flat config for ESLint 9.
 *
 * There was no ESLint config in this repo at all, so `npm run lint` failed outright on every run
 * ("couldn't find an eslint.config.js") and nothing was ever linted. This is the config that was
 * missing, not a migration of an older one.
 *
 * Deliberately NOT type-aware (no `project` in parserOptions). Type-aware linting would need a
 * tsconfig wired up for each of the five sub-projects here — main, renderer, server, web, panel,
 * landing — and would take minutes rather than seconds on a repo this size. The TypeScript
 * compiler already runs over all of it via `build:server` and `build:pos`; ESLint's job here is
 * the things tsc does not look at.
 */

/** Everything ESLint should not read: build output, vendored code, and generated clients. */
const IGNORES = [
  'dist/**',
  'dist-web/**',
  'build/**',
  'release/**',
  'coverage/**',
  'node_modules/**',
  '**/node_modules/**',
  // Sub-projects build into their own folders as well as the root dist.
  'src/web/dist/**',
  'src/panel/dist/**',
  'src/landing/dist/**',
  // The generated SQLite Prisma client: hundreds of thousands of lines of bundled runtime that is
  // regenerated by `prebuild:pos` and gitignored. Linting it is meaningless and very slow.
  'src/generated/**',
];

const TS_FILES = ['src/**/*.ts', 'src/**/*.tsx'];

module.exports = [
  { ignores: IGNORES },

  // ── Plain JavaScript: config files, build scripts, electron-builder config ──────────────────
  {
    files: ['**/*.js', '**/*.cjs', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'commonjs',
      globals: { ...globals.node },
    },
    rules: js.configs.recommended.rules,
  },

  // ── TypeScript ─────────────────────────────────────────────────────────────────────────────
  // Core rules first, so the plugin's `eslint-recommended` below can switch off the ones tsc
  // already does better. Spreading them the other way round silently re-enables core
  // `no-unused-vars` on top of the TypeScript-aware version, and every file reports twice.
  { files: TS_FILES, rules: js.configs.recommended.rules },

  // The plugin's own entries carry no `files`, so they would otherwise claim every file in the
  // repo, including the JS above. Pin all three to the TypeScript glob.
  ...tseslint.configs['flat/recommended'].map((config) => ({ ...config, files: TS_FILES })),

  {
    files: TS_FILES,
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
      // One shared set for browser + node: this repo spans an Electron main process, a React
      // renderer, a NestJS server and three Vite apps, and `no-undef` is off for TypeScript
      // anyway (tsc catches undefined identifiers far better than ESLint can without types).
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      // `_`-prefixed arguments are the established way to mark an intentionally unused parameter,
      // which matters most for Express/Nest handler signatures and IPC callbacks.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],

      // Warn, not error. There are ~215 of these, concentrated at the boundaries where types are
      // genuinely unknown until runtime: IPC payloads crossing the contextBridge, Prisma JSON
      // columns, and third-party SDK responses. They are real debt and should shrink, but making
      // them errors would mean `npm run lint` could never pass, which is how a lint script ends
      // up unused — the state this repo was already in.
      '@typescript-eslint/no-explicit-any': 'warn',

      // Off, because this codebase legitimately matches control characters: GS/RS separators in
      // Asl-Belgisi DataMatrix codes (src/shared/utils/marking.ts), ESC/POS sequences for the
      // thermal printer, and the scanner's own delimiters in POSScreen. Every hit was one of
      // those, so the rule only produced noise here.
      'no-control-regex': 'off',

      // An empty catch is a deliberate "best effort, carry on" throughout the sync and printer
      // paths, and is always written as such. An empty `if`/`while` body still reports.
      'no-empty': ['error', { allowEmptyCatch: true }],

      // `interface DefaultTheme extends Theme {}` is the prescribed styled-components module
      // augmentation, and is the only thing in the four styled.d.ts files.
      '@typescript-eslint/no-empty-object-type': ['error', { allowInterfaces: 'with-single-extends' }],
    },
  },

  // ── React hooks ────────────────────────────────────────────────────────────────────────────
  // The renderer and the three web apps already carry `eslint-disable-next-line
  // react-hooks/exhaustive-deps` comments, but the plugin was never installed — so ESLint failed
  // on "Definition for rule not found" instead of checking anything.
  {
    files: ['src/**/*.tsx'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      // A violation here is a real bug, not a style point.
      'react-hooks/rules-of-hooks': 'error',
      // Advisory: the existing suppressions are considered, not silently correct.
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  // ── Tests ──────────────────────────────────────────────────────────────────────────────────
  {
    files: ['**/*.test.ts', '**/*.test.tsx'],
    rules: {
      // `require()` inside a test is how a jest mock is reached after `jest.mock()` hoisting, and
      // how a module is re-imported under a changed environment. 29 of the 31 hits were this.
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
];
